---
- id: circleci-config-validate
  name: CircleCI config validation
  description: Test if the CircleCI config is well formed.
  entry: pre_commit_hooks/circleci-config-validate.sh
  language: script
  files: ^.circleci/config.yml$

- id: circleci-config-pack
  name: CircleCI config pack
  description: Pack the config, creating the config.yml file
  entry: pre_commit_hooks/circleci-config-pack.sh
  language: script
  files: ^.circleci/config/
  pass_filenames: false

- id: poetry-pytest
  name: CircleCI config validation
  description: Use poetry to run pytest
  entry: pre_commit_hooks/poetry-pytest.sh
  language: script
  pass_filenames: false
  always_run: true

- id: end-of-file-fixer
  name: end of file fixer
  description: end of file fixer
  entry: end-of-file-fixer
  language: python
  types: [text]
  stages: [commit, push, manual]

- id: trailing-whitespace
  name: Trim Trailing Whitespace
  description: This hook trims trailing whitespace.
  entry: trailing-whitespace-fixer
  language: python
  types: [text]
  stages: [commit, push, manual]

- id: pretty-format-json
  name: Pretty format JSON
  description: This hook sets a standard for formatting JSON files.
  entry: pretty-format-json
  language: python
  types: [json]

- id: requirements-txt-fixer
  name: Fix requirements.txt
  description: Sorts entries in requirements.txt
  entry: requirements-txt-fixer
  language: python
  files: requirements.*\.txt$
